/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Data.AlumnoData;
import Data.Conexion;
import Data.NotaData;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import universidadg6.modelo.Alumno;
import universidadg6.modelo.Materia;
import universidadg6.modelo.Nota;

/**
 *
 * @author Martin
 */
public class jifCargaNotas extends javax.swing.JInternalFrame {

    Connection con = Conexion.getConexion();
    AlumnoData aData = new AlumnoData(con);
    NotaData nData = new NotaData();
    List<Alumno> listAlumno;
    private DefaultTableModel tabla;

    public jifCargaNotas() {
        initComponents();
        tabla = new DefaultTableModel();
        llenarCombo();
        armarCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboNota = new javax.swing.JComboBox<>();
        jTxTAlumno = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMaterias = new javax.swing.JTable();
        jButtGuardar = new javax.swing.JButton();
        jButtSalir = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(9, 96, 62));
        jPanel1.setForeground(new java.awt.Color(9, 96, 62));

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 71));
        jLabelTitulo.setText(" Carga de Notas ");
        jLabelTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(8, 131, 80), 2, true));

        jPanel3.setBackground(new java.awt.Color(9, 96, 62));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 71)));
        jPanel3.setForeground(new java.awt.Color(9, 96, 62));

        jComboNota.setBackground(new java.awt.Color(6, 115, 70));
        jComboNota.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jComboNota.setForeground(new java.awt.Color(255, 255, 71));
        jComboNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboNotaActionPerformed(evt);
            }
        });

        jTxTAlumno.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jTxTAlumno.setForeground(new java.awt.Color(255, 255, 71));
        jTxTAlumno.setText("Alumno:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jTxTAlumno)
                .addGap(27, 27, 27)
                .addComponent(jComboNota, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxTAlumno)
                    .addComponent(jComboNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(9, 96, 62));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Materias Del Alumno", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(255, 255, 71))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(9, 96, 62));

        jTableMaterias.setBackground(new java.awt.Color(6, 115, 70));
        jTableMaterias.setForeground(new java.awt.Color(255, 255, 71));
        jTableMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMaterias.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableMaterias);
        if (jTableMaterias.getColumnModel().getColumnCount() > 0) {
            jTableMaterias.getColumnModel().getColumn(0).setResizable(false);
            jTableMaterias.getColumnModel().getColumn(1).setResizable(false);
            jTableMaterias.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jButtGuardar.setBackground(new java.awt.Color(6, 115, 70));
        jButtGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Guardar.png"))); // NOI18N
        jButtGuardar.setText("Guardar");
        jButtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtGuardarActionPerformed(evt);
            }
        });

        jButtSalir.setBackground(new java.awt.Color(6, 115, 70));
        jButtSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtSalir.setText("Salir");
        jButtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(jLabelTitulo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtGuardar)
                .addGap(59, 59, 59)
                .addComponent(jButtSalir)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(32, 32, 32)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtGuardar)
                    .addComponent(jButtSalir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboNotaActionPerformed
        cargarMateriasInscriptas();

    }//GEN-LAST:event_jComboNotaActionPerformed

    private void jButtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtGuardarActionPerformed
        int filasSelec = jTableMaterias.getSelectedRow();
        Alumno a = (Alumno) jComboNota.getSelectedItem();

        try {
            if (filasSelec != -1 && a != null) {
                int idMateria = (int) tabla.getValueAt(filasSelec, 0);
                String nota = (String) tabla.getValueAt(filasSelec, 2);
                double notaA = Double.parseDouble(nota);
                if (notaA <= 10 && notaA >= 0) {
                    nData.actualizarNota(a.getId_alumno(), idMateria, notaA);
                } else {
                    JOptionPane.showMessageDialog(null, "Nota errónea. Coloque nota del 0 al 10", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Seleccione alguna/s materia/s");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Presione ENTER dentro del campo NOTA.", "Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jButtGuardarActionPerformed

    private void jButtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jButtSalirActionPerformed

    private void llenarCombo() {
        listAlumno = aData.obtenerAlumnos();
        for (Alumno alumno : listAlumno) {
            jComboNota.addItem(alumno);
        }
    }

    private void actualizarCombo() {
        int selec = jComboNota.getSelectedIndex();

    }

    private void armarCabeceraTabla() {
        ArrayList<Object> columnas = new ArrayList();
        columnas.add("Código");
        columnas.add("Nombre");
        columnas.add("Nota");

        for (Object aux : columnas) {
            tabla.addColumn(aux);
        }
        jTableMaterias.setModel(tabla);
    }

    private void borrarFilasTabla() {
        if (tabla != null) {
            int aux = tabla.getRowCount() - 1;
            for (int i = aux; i >= 0; i--) {
                tabla.removeRow(i);
            }
        }
    }

    private void cargarMateriasInscriptas() {
        borrarFilasTabla();

        Alumno aSelec = (Alumno) jComboNota.getSelectedItem();
        if (aSelec != null) {
            ArrayList<Materia> listaMateriaIns = (ArrayList) nData.obtenerMateriasInscriptas(aSelec.getId_alumno());

            for (Materia m : listaMateriaIns) {
                Nota n = nData.obtenerInscripcion(aSelec.getId_alumno(), m.getId_materia());
                Object[] filas = new Object[3];
                filas[0] = m.getId_materia();
                filas[1] = m.getNombre();
                filas[2] = n.getNotaAlumno();

                tabla.addRow(filas);
            }
            jTableMaterias.setModel(tabla);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un alumno");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtGuardar;
    private javax.swing.JButton jButtSalir;
    private javax.swing.JComboBox<Alumno> jComboNota;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMaterias;
    private javax.swing.JLabel jTxTAlumno;
    // End of variables declaration//GEN-END:variables
}
