/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Data.Conexion;
import Data.MateriaData;
import java.sql.Connection;
import javax.swing.JOptionPane;
import universidadg6.modelo.Materia;

/**
 *
 * @author Martin
 */
public class jifFormMateria extends javax.swing.JInternalFrame {

    Connection con = Conexion.getConexion();
    MateriaData mData = new MateriaData(con);

    public jifFormMateria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelBuscar = new javax.swing.JPanel();
        jLabelLegajo1 = new javax.swing.JLabel();
        jTxTFBuscarMateria = new javax.swing.JTextField();
        jButtBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTxTFNombre = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTxTFAnio = new javax.swing.JTextField();
        jLabelAnio = new javax.swing.JLabel();
        jCheckBoxActivo = new javax.swing.JCheckBox();
        jLabelActivo = new javax.swing.JLabel();
        jButtGuardar = new javax.swing.JButton();
        jButtActualizar = new javax.swing.JButton();
        jButtBorrar = new javax.swing.JButton();
        jButtLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(9, 96, 62));
        jPanel1.setForeground(new java.awt.Color(9, 96, 62));

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 71));
        jLabelTitulo.setText(" MATERIAS ");
        jLabelTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(8, 131, 80), 2, true));

        jPanelBuscar.setBackground(new java.awt.Color(9, 96, 62));
        jPanelBuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 71)));
        jPanelBuscar.setForeground(new java.awt.Color(9, 96, 62));
        jPanelBuscar.setToolTipText("");

        jLabelLegajo1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelLegajo1.setForeground(new java.awt.Color(255, 255, 71));
        jLabelLegajo1.setText(" Código:");

        jTxTFBuscarMateria.setBackground(new java.awt.Color(6, 115, 70));
        jTxTFBuscarMateria.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTxTFBuscarMateria.setForeground(new java.awt.Color(255, 255, 109));
        jTxTFBuscarMateria.setText("Buscar Materia...");
        jTxTFBuscarMateria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxTFBuscarMateriaFocusGained(evt);
            }
        });
        jTxTFBuscarMateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxTFBuscarMateriaKeyTyped(evt);
            }
        });

        jButtBuscar.setBackground(new java.awt.Color(6, 115, 70));
        jButtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin\\Documents\\GitHub\\UniversidadG6\\src\\images\\Buscar (3).png")); // NOI18N
        jButtBuscar.setText("Buscar");
        jButtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addComponent(jLabelLegajo1)
                .addGap(18, 18, 18)
                .addComponent(jTxTFBuscarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtBuscar)
                .addContainerGap())
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarLayout.createSequentialGroup()
                        .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLegajo1)
                            .addComponent(jButtBuscar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTxTFBuscarMateria, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(9, 96, 62));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Materia", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(255, 255, 71))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(9, 96, 62));

        jTxTFNombre.setBackground(new java.awt.Color(6, 115, 70));
        jTxTFNombre.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTxTFNombre.setForeground(new java.awt.Color(255, 255, 109));
        jTxTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxTFNombreActionPerformed(evt);
            }
        });

        jLabelNombre.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 71));
        jLabelNombre.setText("Nombre:");

        jTxTFAnio.setBackground(new java.awt.Color(6, 115, 70));
        jTxTFAnio.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTxTFAnio.setForeground(new java.awt.Color(255, 255, 109));
        jTxTFAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxTFAnioActionPerformed(evt);
            }
        });
        jTxTFAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxTFAnioKeyTyped(evt);
            }
        });

        jLabelAnio.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelAnio.setForeground(new java.awt.Color(255, 255, 71));
        jLabelAnio.setText("Anio:");

        jCheckBoxActivo.setBackground(new java.awt.Color(6, 115, 70));
        jCheckBoxActivo.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBoxActivo.setSelected(true);

        jLabelActivo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelActivo.setForeground(new java.awt.Color(255, 255, 71));
        jLabelActivo.setText("Activo:");

        jButtGuardar.setBackground(new java.awt.Color(6, 115, 70));
        jButtGuardar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButtGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin\\Documents\\GitHub\\UniversidadG6\\src\\images\\Guardar.png")); // NOI18N
        jButtGuardar.setText("Guardar");
        jButtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtGuardarActionPerformed(evt);
            }
        });

        jButtActualizar.setBackground(new java.awt.Color(6, 115, 70));
        jButtActualizar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButtActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButtActualizar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin\\Documents\\GitHub\\UniversidadG6\\src\\images\\Actualizar.png")); // NOI18N
        jButtActualizar.setText("Actualizar");
        jButtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtActualizarActionPerformed(evt);
            }
        });

        jButtBorrar.setBackground(new java.awt.Color(6, 115, 70));
        jButtBorrar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButtBorrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtBorrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin\\Documents\\GitHub\\UniversidadG6\\src\\images\\borrar.png")); // NOI18N
        jButtBorrar.setText("Borrar");
        jButtBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtBorrarActionPerformed(evt);
            }
        });

        jButtLimpiar.setBackground(new java.awt.Color(6, 115, 70));
        jButtLimpiar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButtLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButtLimpiar.setText("Limpiar");
        jButtLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelAnio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxTFAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelActivo)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxActivo)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButtGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtLimpiar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTxTFNombre))
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAnio)
                    .addComponent(jTxTFAnio))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelActivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtGuardar)
                            .addComponent(jButtActualizar)
                            .addComponent(jButtBorrar)
                            .addComponent(jButtLimpiar)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBoxActivo)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emblem.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 71));
        jLabel3.setText("Universidad Grupo 6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(217, 217, 217)
                            .addComponent(jLabelTitulo))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(216, 216, 216))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtBuscarActionPerformed

        int codigo = Integer.parseInt(jTxTFBuscarMateria.getText());
        Materia m = mData.buscarMateria(codigo);
        if (m != null) {
            mData.buscarMateria(codigo);
            jTxTFNombre.setText(m.getNombre());
            jTxTFAnio.setText(String.valueOf(m.getAnio()));
            jCheckBoxActivo.setSelected(m.isActivo());
        } else {
            JOptionPane.showMessageDialog(null, "No se ha encontrado la materia","Error",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtBuscarActionPerformed

    private void jTxTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxTFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxTFNombreActionPerformed

    private void jTxTFAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxTFAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxTFAnioActionPerformed

    private void jButtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtGuardarActionPerformed
        int anio = Integer.parseInt(jTxTFAnio.getText());
        String nombreMateria = jTxTFNombre.getText();
        boolean activo = jCheckBoxActivo.isSelected();
        Materia m = new Materia(nombreMateria, anio, activo);
        mData.guardarMateria(m);
        jTxTFBuscarMateria.setText("");
        jTxTFNombre.setText("");
        jTxTFAnio.setText("");
    }//GEN-LAST:event_jButtGuardarActionPerformed

    private void jButtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtActualizarActionPerformed
        int id = Integer.parseInt(jTxTFBuscarMateria.getText());
        String nombre = jTxTFNombre.getText();
        int anio = Integer.parseInt(jTxTFAnio.getText());
        boolean estado = jCheckBoxActivo.isSelected();
        Materia m = new Materia(id, nombre, anio, estado);
        mData.actualizarMateria(m, Integer.parseInt(jTxTFBuscarMateria.getText()));
        jTxTFBuscarMateria.setText("");
        jTxTFNombre.setText("");
        jTxTFAnio.setText("");
    }//GEN-LAST:event_jButtActualizarActionPerformed

    private void jButtBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtBorrarActionPerformed
        int codigo = Integer.parseInt(jTxTFBuscarMateria.getText());
        mData.borrarMateria(codigo);
        jTxTFBuscarMateria.setText("");
        jTxTFNombre.setText("");
        jTxTFAnio.setText("");
    }//GEN-LAST:event_jButtBorrarActionPerformed

    private void jButtLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtLimpiarActionPerformed
        jTxTFBuscarMateria.setText("");
        jTxTFNombre.setText("");
        jTxTFAnio.setText("");
    }//GEN-LAST:event_jButtLimpiarActionPerformed

    private void jTxTFBuscarMateriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxTFBuscarMateriaKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jTxTFBuscarMateriaKeyTyped

    private void jTxTFAnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxTFAnioKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jTxTFAnioKeyTyped

    private void jTxTFBuscarMateriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxTFBuscarMateriaFocusGained
        jTxTFBuscarMateria.setText("");
    }//GEN-LAST:event_jTxTFBuscarMateriaFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtActualizar;
    private javax.swing.JButton jButtBorrar;
    private javax.swing.JButton jButtBuscar;
    private javax.swing.JButton jButtGuardar;
    private javax.swing.JButton jButtLimpiar;
    private javax.swing.JCheckBox jCheckBoxActivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelActivo;
    private javax.swing.JLabel jLabelAnio;
    private javax.swing.JLabel jLabelLegajo1;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JTextField jTxTFAnio;
    private javax.swing.JTextField jTxTFBuscarMateria;
    private javax.swing.JTextField jTxTFNombre;
    // End of variables declaration//GEN-END:variables
}
