/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Data.AlumnoData;
import Data.Conexion;
import java.sql.Connection;
import java.time.LocalDate;
import java.util.Calendar;
import universidadg6.modelo.Alumno;

/**
 *
 * @author Martin
 */
public class jifFormAlumno extends javax.swing.JInternalFrame {
    
    Connection con = Conexion.getConexion();
    AlumnoData aData = new AlumnoData(con);
    
    public jifFormAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelBuscar = new javax.swing.JPanel();
        jLabelLegajo = new javax.swing.JLabel();
        jTxTFBuscarAlumno = new javax.swing.JTextField();
        jButtBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTxTFDNI = new javax.swing.JTextField();
        jLabelDNI = new javax.swing.JLabel();
        jTxTFApellido = new javax.swing.JTextField();
        jLabelDNI1 = new javax.swing.JLabel();
        jTxTFNombre = new javax.swing.JTextField();
        jLabelDNI2 = new javax.swing.JLabel();
        jLabelDNI3 = new javax.swing.JLabel();
        jCheckBoxActivo = new javax.swing.JCheckBox();
        jLabelActivo = new javax.swing.JLabel();
        jButtGuardar = new javax.swing.JButton();
        jButtActualizar = new javax.swing.JButton();
        jButtBorrar = new javax.swing.JButton();
        jButtLimpiar = new javax.swing.JButton();
        jDCFechaNac = new com.toedter.calendar.JDateChooser();
        jTxTFFechaNac = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(9, 96, 62));
        jPanel1.setForeground(new java.awt.Color(9, 96, 62));

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 71));
        jLabelTitulo.setText(" Alumnos ");
        jLabelTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(8, 131, 80), 2, true));

        jPanelBuscar.setBackground(new java.awt.Color(9, 96, 62));
        jPanelBuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 71)));
        jPanelBuscar.setForeground(new java.awt.Color(9, 96, 62));
        jPanelBuscar.setToolTipText("");

        jLabelLegajo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelLegajo.setForeground(new java.awt.Color(255, 255, 71));
        jLabelLegajo.setText(" Legajo:");

        jTxTFBuscarAlumno.setBackground(new java.awt.Color(6, 115, 70));
        jTxTFBuscarAlumno.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTxTFBuscarAlumno.setForeground(new java.awt.Color(255, 255, 109));
        jTxTFBuscarAlumno.setText("Buscar Alumno...");

        jButtBuscar.setBackground(new java.awt.Color(6, 115, 70));
        jButtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtBuscar.setText("Buscar");
        jButtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addComponent(jLabelLegajo)
                .addGap(18, 18, 18)
                .addComponent(jTxTFBuscarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButtBuscar)
                .addContainerGap())
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarLayout.createSequentialGroup()
                        .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLegajo)
                            .addComponent(jButtBuscar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTxTFBuscarAlumno, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(9, 96, 62));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alumno", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(255, 255, 71))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(9, 96, 62));

        jTxTFDNI.setBackground(new java.awt.Color(6, 115, 70));
        jTxTFDNI.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTxTFDNI.setForeground(new java.awt.Color(255, 255, 109));
        jTxTFDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxTFDNIActionPerformed(evt);
            }
        });

        jLabelDNI.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelDNI.setForeground(new java.awt.Color(255, 255, 71));
        jLabelDNI.setText("DNI:");

        jTxTFApellido.setBackground(new java.awt.Color(6, 115, 70));
        jTxTFApellido.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTxTFApellido.setForeground(new java.awt.Color(255, 255, 109));
        jTxTFApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxTFApellidoActionPerformed(evt);
            }
        });

        jLabelDNI1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelDNI1.setForeground(new java.awt.Color(255, 255, 71));
        jLabelDNI1.setText("Apellido:");

        jTxTFNombre.setBackground(new java.awt.Color(6, 115, 70));
        jTxTFNombre.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTxTFNombre.setForeground(new java.awt.Color(255, 255, 109));
        jTxTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxTFNombreActionPerformed(evt);
            }
        });

        jLabelDNI2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelDNI2.setForeground(new java.awt.Color(255, 255, 71));
        jLabelDNI2.setText("Nombre:");

        jLabelDNI3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelDNI3.setForeground(new java.awt.Color(255, 255, 71));
        jLabelDNI3.setText("FechaNacimiento:");

        jCheckBoxActivo.setBackground(new java.awt.Color(6, 115, 70));
        jCheckBoxActivo.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBoxActivo.setSelected(true);

        jLabelActivo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelActivo.setForeground(new java.awt.Color(255, 255, 71));
        jLabelActivo.setText("Activo:");

        jButtGuardar.setBackground(new java.awt.Color(6, 115, 70));
        jButtGuardar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButtGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtGuardar.setText("Guardar");
        jButtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtGuardarActionPerformed(evt);
            }
        });

        jButtActualizar.setBackground(new java.awt.Color(6, 115, 70));
        jButtActualizar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButtActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButtActualizar.setText("Actualizar");
        jButtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtActualizarActionPerformed(evt);
            }
        });

        jButtBorrar.setBackground(new java.awt.Color(6, 115, 70));
        jButtBorrar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButtBorrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtBorrar.setText("Borrar");

        jButtLimpiar.setBackground(new java.awt.Color(6, 115, 70));
        jButtLimpiar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButtLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButtLimpiar.setText("Limpiar");

        jDCFechaNac.setBackground(new java.awt.Color(6, 115, 70));
        jDCFechaNac.setForeground(new java.awt.Color(6, 115, 70));
        jDCFechaNac.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jDCFechaNacAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jTxTFFechaNac.setBackground(new java.awt.Color(6, 115, 70));
        jTxTFFechaNac.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTxTFFechaNac.setForeground(new java.awt.Color(255, 255, 109));
        jTxTFFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxTFFechaNacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelDNI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxTFDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelDNI1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                .addComponent(jTxTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelDNI2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelActivo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxActivo))
                                    .addComponent(jLabelDNI3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxTFFechaNac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jDCFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButtGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtLimpiar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDNI)
                    .addComponent(jTxTFDNI))
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDNI1)
                    .addComponent(jTxTFApellido))
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDNI2)
                    .addComponent(jTxTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDNI3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDCFechaNac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelActivo)
                            .addComponent(jCheckBoxActivo)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jTxTFFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtGuardar)
                    .addComponent(jButtActualizar)
                    .addComponent(jButtBorrar)
                    .addComponent(jButtLimpiar)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabelTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxTFDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxTFDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxTFDNIActionPerformed

    private void jTxTFApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxTFApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxTFApellidoActionPerformed

    private void jTxTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxTFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxTFNombreActionPerformed

    private void jButtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtGuardarActionPerformed
        Alumno alumno = new Alumno();
        long dni = Long.parseLong(jTxTFDNI.getText());
        String apellido = jTxTFApellido.getText();
        String nombre = jTxTFNombre.getText();
        boolean activo = jCheckBoxActivo.isSelected();
        int dia = jDCFechaNac.getCalendar().get(Calendar.DAY_OF_MONTH);
        int mes = jDCFechaNac.getCalendar().get(Calendar.MONTH);
        int anio = jDCFechaNac.getCalendar().get(Calendar.YEAR);
        
        alumno.setDni(dni);
        alumno.setApellido(apellido);
        alumno.setNombre(nombre);
        alumno.setFechaNacimiento(LocalDate.of(anio, mes, dia));
        alumno.setActivo(activo);
        aData.guardarAlumno(alumno);
        jTxTFDNI.setText("");
        jTxTFApellido.setText("");
        jTxTFNombre.setText("");
        jTxTFFechaNac.setText("");
        jTxTFFechaNac.setText("");
    }//GEN-LAST:event_jButtGuardarActionPerformed

    private void jButtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtBuscarActionPerformed
        Alumno a = aData.buscarAlumno(Integer.parseInt(jTxTFBuscarAlumno.getText()));
        jTxTFDNI.setText(String.valueOf(a.getDni()));
        jTxTFApellido.setText(a.getApellido());
        jTxTFNombre.setText(a.getNombre());
        jTxTFFechaNac.setText("");
        jTxTFFechaNac.setText(a.getFechaNacimiento().toString());
    }//GEN-LAST:event_jButtBuscarActionPerformed

    private void jButtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtActualizarActionPerformed
        Alumno a = aData.buscarAlumno(Integer.parseInt(jTxTFBuscarAlumno.getText()));
        aData.actualizarAlumno(new Alumno(Integer.parseInt(jTxTFDNI.getText()), jTxTFApellido.getText(), jTxTFNombre.getText(), LocalDate.MIN, jCheckBoxActivo.areFocusTraversalKeysSet(1)), Integer.parseInt(jTxTFBuscarAlumno.getText()));
    }//GEN-LAST:event_jButtActualizarActionPerformed

    private void jDCFechaNacAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDCFechaNacAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jDCFechaNacAncestorAdded

    private void jTxTFFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxTFFechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxTFFechaNacActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtActualizar;
    private javax.swing.JButton jButtBorrar;
    private javax.swing.JButton jButtBuscar;
    private javax.swing.JButton jButtGuardar;
    private javax.swing.JButton jButtLimpiar;
    private javax.swing.JCheckBox jCheckBoxActivo;
    private com.toedter.calendar.JDateChooser jDCFechaNac;
    private javax.swing.JLabel jLabelActivo;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelDNI1;
    private javax.swing.JLabel jLabelDNI2;
    private javax.swing.JLabel jLabelDNI3;
    private javax.swing.JLabel jLabelLegajo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JTextField jTxTFApellido;
    private javax.swing.JTextField jTxTFBuscarAlumno;
    private javax.swing.JTextField jTxTFDNI;
    private javax.swing.JTextField jTxTFFechaNac;
    private javax.swing.JTextField jTxTFNombre;
    // End of variables declaration//GEN-END:variables
}
