/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Data.AlumnoData;
import Data.Conexion;
import Data.NotaData;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import universidadg6.modelo.Alumno;
import universidadg6.modelo.Materia;
import universidadg6.modelo.Nota;

/**
 *
 * @author Martin
 */
public class jifInscripcion extends javax.swing.JInternalFrame {

    Connection con = Conexion.getConexion();
    AlumnoData aData = new AlumnoData(con);
    NotaData nData = new NotaData();
    List<Alumno> listAlumno;
    private DefaultTableModel tabla;

    public jifInscripcion() {
        initComponents();
        llenarCombo();
        tabla = new DefaultTableModel();
        armarCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtInscribir = new javax.swing.JButton();
        jButtAnularInscrip = new javax.swing.JButton();
        jButtSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMaterias = new javax.swing.JTable();
        jRButtInscrip = new javax.swing.JRadioButton();
        jRButtNoInscrip = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jComboInscripcion = new javax.swing.JComboBox<>();
        jTxTAlumno = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(9, 96, 62));
        jPanel1.setForeground(new java.awt.Color(9, 96, 62));

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 71));
        jLabelTitulo.setText("Inscripción");
        jLabelTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(8, 131, 80), 2, true));

        jButtInscribir.setBackground(new java.awt.Color(6, 115, 70));
        jButtInscribir.setForeground(new java.awt.Color(255, 255, 255));
        jButtInscribir.setText("Inscribir");
        jButtInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtInscribirActionPerformed(evt);
            }
        });

        jButtAnularInscrip.setBackground(new java.awt.Color(6, 115, 70));
        jButtAnularInscrip.setForeground(new java.awt.Color(255, 255, 255));
        jButtAnularInscrip.setText("Anular Inscripción");
        jButtAnularInscrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtAnularInscripActionPerformed(evt);
            }
        });

        jButtSalir.setBackground(new java.awt.Color(6, 115, 70));
        jButtSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtSalir.setText("Salir");

        jPanel2.setBackground(new java.awt.Color(9, 96, 62));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Materias", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(255, 255, 71))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(9, 96, 62));

        jTableMaterias.setBackground(new java.awt.Color(6, 115, 70));
        jTableMaterias.setForeground(new java.awt.Color(255, 255, 71));
        jTableMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Anio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMaterias);

        jRButtInscrip.setBackground(new java.awt.Color(6, 115, 70));
        jRButtInscrip.setForeground(new java.awt.Color(255, 255, 71));
        jRButtInscrip.setText("Inscriptas");
        jRButtInscrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRButtInscripActionPerformed(evt);
            }
        });

        jRButtNoInscrip.setBackground(new java.awt.Color(6, 115, 70));
        jRButtNoInscrip.setForeground(new java.awt.Color(255, 255, 71));
        jRButtNoInscrip.setText("No Inscriptas");
        jRButtNoInscrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRButtNoInscripActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jRButtInscrip, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(243, 243, 243)
                        .addComponent(jRButtNoInscrip))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRButtInscrip)
                    .addComponent(jRButtNoInscrip))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(9, 96, 62));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 71)));
        jPanel3.setForeground(new java.awt.Color(9, 96, 62));

        jComboInscripcion.setBackground(new java.awt.Color(6, 115, 70));
        jComboInscripcion.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jComboInscripcion.setForeground(new java.awt.Color(255, 255, 71));
        jComboInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboInscripcionActionPerformed(evt);
            }
        });

        jTxTAlumno.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jTxTAlumno.setForeground(new java.awt.Color(255, 255, 71));
        jTxTAlumno.setText("Alumno:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jTxTAlumno)
                .addGap(27, 27, 27)
                .addComponent(jComboInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxTAlumno)
                    .addComponent(jComboInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jButtInscribir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtAnularInscrip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtInscribir)
                    .addComponent(jButtAnularInscrip)
                    .addComponent(jButtSalir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRButtNoInscripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRButtNoInscripActionPerformed
        if (jRButtNoInscrip.isSelected()) {
            jRButtInscrip.setSelected(false);
            jButtAnularInscrip.setEnabled(false);
            jButtInscribir.setEnabled(true);
            cargarMateriasNoInscriptas();
        } else if (!jRButtNoInscrip.isSelected()) {
            borrarFilasTabla();
        }

    }//GEN-LAST:event_jRButtNoInscripActionPerformed

    private void jRButtInscripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRButtInscripActionPerformed
        if (jRButtInscrip.isSelected()) {
            jRButtNoInscrip.setSelected(false);
            jButtAnularInscrip.setEnabled(true);
            jButtInscribir.setEnabled(false);
            cargarMateriasInscriptas();
        } else if (!jRButtInscrip.isSelected()) {
            borrarFilasTabla();
        }

    }//GEN-LAST:event_jRButtInscripActionPerformed

    private void jComboInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboInscripcionActionPerformed

    }//GEN-LAST:event_jComboInscripcionActionPerformed

    private void jButtInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtInscribirActionPerformed
        int filasSelec = jTableMaterias.getSelectedRow();
        Alumno a = (Alumno) jComboInscripcion.getSelectedItem();

        if (filasSelec != -1 && a != null) {
            int idMateria = (int) tabla.getValueAt(filasSelec, 0);
            String nombreMateria = (String) tabla.getValueAt(filasSelec, 1);
            int anio = (int) tabla.getValueAt(filasSelec, 2);
            Materia m = new Materia(idMateria, nombreMateria, anio, true);
            Nota n = new Nota(a, m, -1);
            nData.guardarInscripcion(n);
            borrarFilasTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione alguna/s materia/s");
        }

    }//GEN-LAST:event_jButtInscribirActionPerformed

    private void jButtAnularInscripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtAnularInscripActionPerformed
        int filasSelec[] = jTableMaterias.getSelectedRows();
        Alumno a = (Alumno) jComboInscripcion.getSelectedItem();
        for (int i : filasSelec) {
            if (filasSelec[i] != -1 && a != null) {
                int idMateria = (int) tabla.getValueAt(filasSelec[i], 0);
                nData.borrarInscripcion(a.getId_alumno(), idMateria);
                borrarFilasTabla();
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione alguna/s materia/s");
            }
        }
    }//GEN-LAST:event_jButtAnularInscripActionPerformed

    private void llenarCombo() {
        listAlumno = aData.obtenerAlumnos();
        for (Alumno alumno : listAlumno) {
            jComboInscripcion.addItem(alumno);
        }
    }

    private void borrarFilasTabla() {
        if (tabla != null) {
            int aux = tabla.getRowCount() - 1;
            for (int i = aux; i >= 0; i--) {
                tabla.removeRow(i);
            }
        }
    }

    private void cargarMateriasNoInscriptas() {
        borrarFilasTabla();
        Alumno aSelec = (Alumno) jComboInscripcion.getSelectedItem();
        if (aSelec != null) {
            ArrayList<Materia> listaMateriaNoIns = (ArrayList) nData.obtenerMateriasNoInscriptas(aSelec.getId_alumno());

            for (Materia m : listaMateriaNoIns) {
                tabla.addRow(new Object[]{m.getId_materia(), m.getNombre(), m.getAnio()});
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un alumno");
        }
    }

    private void cargarMateriasInscriptas() {
        borrarFilasTabla();
        Alumno aSelec = (Alumno) jComboInscripcion.getSelectedItem();
        if (aSelec != null) {
            ArrayList<Materia> listaMateriaIns = (ArrayList) nData.obtenerMateriasInscriptas(aSelec.getId_alumno());

            for (Materia m : listaMateriaIns) {
                tabla.addRow(new Object[]{m.getId_materia(), m.getNombre(), m.getAnio()});
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un alumno");
        }
    }

    private void armarCabeceraTabla() {
        ArrayList<Object> columnas = new ArrayList();
        columnas.add("Código");
        columnas.add("Nombre");
        columnas.add("Año");

        for (Object aux : columnas) {
            tabla.addColumn(aux);
        }
        jTableMaterias.setModel(tabla);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtAnularInscrip;
    private javax.swing.JButton jButtInscribir;
    private javax.swing.JButton jButtSalir;
    private javax.swing.JComboBox<Alumno> jComboInscripcion;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRButtInscrip;
    private javax.swing.JRadioButton jRButtNoInscrip;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMaterias;
    private javax.swing.JLabel jTxTAlumno;
    // End of variables declaration//GEN-END:variables

}
